#!/bin/bash

usage() {
  echo "Usage: no parameters attempts to perform a fresh install"
  echo "       [-r] reinstall application." 1>&2;
  echo "       [-n] re/install dependencies." 1>&2;
  echo "       [-s] install/reset settings." 1>&2;
  echo "       [-g] keep git." 1>&2;
  echo "       [-h] show usage." 1>&2;
  exit 1;
}

depsInstalled=false
settingsInstalled=false
verbose=false
keepGit=false
runDeps=false
runSettings=false
runFinalize=false

installDependencies() {
  if [ "$depsInstalled" = false ]; then
    echo " - Installing dependencies" >&2
    depsInstalled=true

    if [ -d node_modules ]; then
      echo "Deleteing node_modules"

      rm -rf node_modules >&2
    fi

    yarn install
  fi
}

installSettings() {
  if [ "$settingsInstalled" = false ]; then
    echo " - Installing settings" >&2
    settingsInstalled=true

    if [ -f "src/settings.json" ]; then
      rm "src/settings.json"
    fi

    cp src/default-settings.json src/settings.json
  fi
}

finalize(){
  if [ "$1" = false ]; then
    rm -rf .git
  fi

  if [ -d docs ]; then
    rm -rf docs
  fi

  if [ -f _config.yml ]; then
    rm -f _config.yml
  fi

  touch .installed
}


  while getopts ":ns :rg :h" opt; do
    case "${opt}" in
      r)
        runDeps=true
        runSettings=true
        runFinalize=true
        yarn run build

        echo "Application reinstalled"
        echo "yarn run watch to watch directory"
        echo "yarn run dev and load http://localhost:8080"
        ;;
      n)
        runDeps=true
        ;;
      s)
        runSettings=true
        ;;
      g)
        keepGit=true
        ;;
      h)
        usage
        ;;
    esac
  done
  shift $((OPTIND-1))

if [ -f .installed ]; then

  if [ $OPTIND -eq 1 ]; then
    echo "Application already installed."
  fi

  if [ "$runDeps" = true ]; then
        installDependencies
  fi

  if [ "$runSettings" = true ]; then
        installSettings
  fi

  if [ "$runFinalize" = true ]; then
        finalize "$keepGit"
  fi

  exit 0
fi

installDependencies
installSettings
finalize "$keepGit"
yarn run build

echo "Application installed."
echo "command: yarn run watch\n\nto watch directory"
echo "command: yarn run dev\n\nthen load http://localhost:8080"
